### ISSUE TITLE
Action Ideas

### ISSUE THREAD

**Issue by ThePreviousOne** [biotinker/LibreTasks#191]
I think it would be cool to have "settings" as Actions, then you could create tasks like: On location change, enable/disable WiFi/data. Or Time is..., Change screen brightness.

**Comment by biotinker** [comment]
Both of these are actually already implemented! Wifi, brightness control, and a number of other settings-related actions are under the "Libretasks" section of "actions". I agree, they should probably be split out to a "Settings" group.
