### ISSUE TITLE
add bluetooth control

### ISSUE THREAD

**Issue by tbeitter** [biotinker/LibreTasks#197]
one of the most important tasks for me (and many colleagues using bt-headseats during the workday) would be to enable BT on incoming/outgoing phone calls and to switch it off after you hung up.

**Comment by biotinker** [comment]
Turning bluetooth on/off should be very easy to implement, that's pretty high on the list. There's already a trigger for an incoming call, I can see about adding one for outgoing calls as well.

**Comment by tbeitter** [comment]
that would be really nice as right now the only way to achieve this are all those crappy auto-bt apps on the play store :+1:

**Comment by biotinker** [comment]
This will be in the next release, which should be out before the end of the weekend.

**Comment by biotinker** [comment]
Bluetooth support has been completed and will be included in version 0.5.0
