### ISSUE TITLE
GPS is being queried permanently, whether or not it is needed

### ISSUE THREAD

**Issue by mvglasow** [biotinker/LibreTasks#216]
When LibreTasks is running, it constantly queries GPS, regardless of whether it’s needed for any active rule. I fear this is going to drain the battery pretty quickly.

I suggest requesting GPS location updates only when a location-based rule is active.

**Comment by mvglasow** [comment]
After a few weeks of digging through the code, I guess this might be difficult to implement, as location is a default attribute, available with any event, and which can occur in a variety of places:

* Location events
* Location-based filters
* Location being used as an attribute in actions

The first two are probably easy to catch, but getting a list of all rules which use location attributes in their actions might not be doable in a manner that is guaranteed to be work even with future actions.

As a workaround, we might do the following:

* Use the passive location provider instead of GPS. This will piggy-back on any other location-aware application—if any other app gets a location, we get a copy of that. Battery drain next to zero, but no guarantee on frequency of events.
* Periodically poll location. We could implement this as a rule: on certain events (phone moves to a different cell, once every X minutes, X minutes after last location update, ...), request a location update. This would require new events and a new action. Battery drain can be controlled through the choice of events (and intervals) which trigger location polls.
* Let the user select where to get the location from (GPS, network, or the first provider to respond). This could be implemented as a parameter in the location update action.

Any opinions on that?

**Comment by mvglasow** [comment]
Just another thought that came to my mind: make the location source configurable via two options in Preferences:

* Check box: Use passive location provider (note: enabling this will save battery, but location-based rules may not fire accurately unless another app is currently accessing location information)
* Option button: Location provider
  * GPS
  * Network
  * Other location providers present (if any, apart from the passive provider)
  * Any

If the first option is selected, subscribe (only) to the passive location provider. When a location is received, process it only if it matches the provider selected in the second option (“any” will match any provider).

If the first option is not selected, use the second option to decide which location provider to subscribe to (for “any”, subscribe to all location providers available).

On top of that, we can still implement “request location updates” as an action, potentially with the following parameters:

* Request updates from a specific provider (which may be different from the one in Preferences), or from all providers
* Unregister location listener after a certain timeout, or upon receiving a location, or through a separate action

**Comment by mvglasow** [comment]
Basic functionality (select passive location provider or a specific one) is available in #227 . Changes currently require a restart of LibreTasks (or some way of re-registering with the location provider). The optional parts are not part of the pull request. Default behavior is to use GPS, as before.

**Comment by emil-petersen** [comment]
@mvglasow Hey, I am interested in using LibreTasks since I am running on an android version with no google services (copperhead). Thank you for addressing this issue. I will experiment with the location trigger, and depending on how it works out I may be looking to contribute some actions / triggers or other help with the project.

**Comment by biotinker** [comment]
Closing as this is fixed in newest release
