### ISSUE TITLE
Update F-Droid relase

### ISSUE THREAD

**Issue by SkyWheel** [biotinker/LibreTasks#230]
The fdroid version seems to be abandoned. Who can sort out update for the fdroid repo?

**Comment by ildar** [comment]
1. checking https://f-droid.org/wiki/page/libretasks.app looks allright.
2. But then searching fdroiddata emerges this:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3039
3. So the good place for further discussion is right there.

**Comment by spaetz** [comment]
Given that 0.7.1 seems to be available via fdroid, this.issue can be closed now?!?

**Comment by biotinker** [comment]
Yep, closing
